//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkXUI.Resources.Views.ParkingSites {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ParkXUI.Resources.Views.ParkingSites.index", typeof(index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string menu_home {
            get {
                return ResourceManager.GetString("menu_home", resourceCulture);
            }
        }
        
        internal static string find_car_park {
            get {
                return ResourceManager.GetString("find_car_park", resourceCulture);
            }
        }
        
        internal static string vehicle_unit {
            get {
                return ResourceManager.GetString("vehicle_unit", resourceCulture);
            }
        }
        
        internal static string max_car {
            get {
                return ResourceManager.GetString("max_car", resourceCulture);
            }
        }
        
        internal static string compare {
            get {
                return ResourceManager.GetString("compare", resourceCulture);
            }
        }
        
        internal static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        internal static string park_service {
            get {
                return ResourceManager.GetString("park_service", resourceCulture);
            }
        }
        
        internal static string parking_rate {
            get {
                return ResourceManager.GetString("parking_rate", resourceCulture);
            }
        }
        
        internal static string typeOfCar {
            get {
                return ResourceManager.GetString("typeOfCar", resourceCulture);
            }
        }
        
        internal static string Hourly {
            get {
                return ResourceManager.GetString("Hourly", resourceCulture);
            }
        }
        
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        internal static string contactUS {
            get {
                return ResourceManager.GetString("contactUS", resourceCulture);
            }
        }
        
        internal static string FurtherInformation {
            get {
                return ResourceManager.GetString("FurtherInformation", resourceCulture);
            }
        }
        
        internal static string NEARBY {
            get {
                return ResourceManager.GetString("NEARBY", resourceCulture);
            }
        }
        
        internal static string car_concurrent {
            get {
                return ResourceManager.GetString("car_concurrent", resourceCulture);
            }
        }
    }
}
