//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkXUI.Resources.Views.Shared {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Layout_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ParkXUI.Resources.Views.Shared._Layout_en", typeof(_Layout_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        internal static string FindCar {
            get {
                return ResourceManager.GetString("FindCar", resourceCulture);
            }
        }
        
        internal static string FooterDes {
            get {
                return ResourceManager.GetString("FooterDes", resourceCulture);
            }
        }
        
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        internal static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        internal static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        internal static string Subdistrict {
            get {
                return ResourceManager.GetString("Subdistrict", resourceCulture);
            }
        }
        
        internal static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        internal static string specialDes {
            get {
                return ResourceManager.GetString("specialDes", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string PARKING_SOLUTIONS {
            get {
                return ResourceManager.GetString("PARKING_SOLUTIONS", resourceCulture);
            }
        }
        
        internal static string NEWS_PROMOTIONS {
            get {
                return ResourceManager.GetString("NEWS_PROMOTIONS", resourceCulture);
            }
        }
        
        internal static string CONTACT_US {
            get {
                return ResourceManager.GetString("CONTACT_US", resourceCulture);
            }
        }
        
        internal static string menu_parksolution {
            get {
                return ResourceManager.GetString("menu_parksolution", resourceCulture);
            }
        }
        
        internal static string menu_about {
            get {
                return ResourceManager.GetString("menu_about", resourceCulture);
            }
        }
        
        internal static string menu_newAndPromotions {
            get {
                return ResourceManager.GetString("menu_newAndPromotions", resourceCulture);
            }
        }
        
        internal static string menu_new {
            get {
                return ResourceManager.GetString("menu_new", resourceCulture);
            }
        }
        
        internal static string menu_promotions {
            get {
                return ResourceManager.GetString("menu_promotions", resourceCulture);
            }
        }
        
        internal static string menu_contactUS {
            get {
                return ResourceManager.GetString("menu_contactUS", resourceCulture);
            }
        }
        
        internal static string menu_personal_menage {
            get {
                return ResourceManager.GetString("menu_personal_menage", resourceCulture);
            }
        }
        
        internal static string menu_package_info {
            get {
                return ResourceManager.GetString("menu_package_info", resourceCulture);
            }
        }
        
        internal static string menu_vehicle_info {
            get {
                return ResourceManager.GetString("menu_vehicle_info", resourceCulture);
            }
        }
        
        internal static string menu_logout {
            get {
                return ResourceManager.GetString("menu_logout", resourceCulture);
            }
        }
        
        internal static string menu_login {
            get {
                return ResourceManager.GetString("menu_login", resourceCulture);
            }
        }
        
        internal static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
