//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkXUI.Resources.Views.Package {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PackageDetail {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackageDetail() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ParkXUI.Resources.Views.Package.PackageDetail", typeof(PackageDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string menu_home {
            get {
                return ResourceManager.GetString("menu_home", resourceCulture);
            }
        }
        
        internal static string menu_find_park {
            get {
                return ResourceManager.GetString("menu_find_park", resourceCulture);
            }
        }
        
        internal static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        internal static string packageName {
            get {
                return ResourceManager.GetString("packageName", resourceCulture);
            }
        }
        
        internal static string Member_type {
            get {
                return ResourceManager.GetString("Member_type", resourceCulture);
            }
        }
        
        internal static string packageType {
            get {
                return ResourceManager.GetString("packageType", resourceCulture);
            }
        }
        
        internal static string vehicleType {
            get {
                return ResourceManager.GetString("vehicleType", resourceCulture);
            }
        }
        
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        internal static string qtyOfCar {
            get {
                return ResourceManager.GetString("qtyOfCar", resourceCulture);
            }
        }
        
        internal static string lotOfCar {
            get {
                return ResourceManager.GetString("lotOfCar", resourceCulture);
            }
        }
        
        internal static string OvernightRate {
            get {
                return ResourceManager.GetString("OvernightRate", resourceCulture);
            }
        }
        
        internal static string DepositedRate {
            get {
                return ResourceManager.GetString("DepositedRate", resourceCulture);
            }
        }
        
        internal static string additionalPrice {
            get {
                return ResourceManager.GetString("additionalPrice", resourceCulture);
            }
        }
        
        internal static string addSlotOfCar {
            get {
                return ResourceManager.GetString("addSlotOfCar", resourceCulture);
            }
        }
        
        internal static string addQtyOfCar {
            get {
                return ResourceManager.GetString("addQtyOfCar", resourceCulture);
            }
        }
        
        internal static string siteAvailable {
            get {
                return ResourceManager.GetString("siteAvailable", resourceCulture);
            }
        }
        
        internal static string menu_park_site {
            get {
                return ResourceManager.GetString("menu_park_site", resourceCulture);
            }
        }
        
        internal static string Pacakage_Detail {
            get {
                return ResourceManager.GetString("Pacakage_Detail", resourceCulture);
            }
        }
        
        internal static string BuyPackage {
            get {
                return ResourceManager.GetString("BuyPackage", resourceCulture);
            }
        }
    }
}
