//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkXUI.Resources.Views.Package {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PurchasePackage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchasePackage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ParkXUI.Resources.Views.Package.PurchasePackage", typeof(PurchasePackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PackageName {
            get {
                return ResourceManager.GetString("PackageName", resourceCulture);
            }
        }
        
        internal static string PackageType {
            get {
                return ResourceManager.GetString("PackageType", resourceCulture);
            }
        }
        
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        internal static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        internal static string PricePerCar {
            get {
                return ResourceManager.GetString("PricePerCar", resourceCulture);
            }
        }
        
        internal static string UnitCar {
            get {
                return ResourceManager.GetString("UnitCar", resourceCulture);
            }
        }
        
        internal static string UnitCars {
            get {
                return ResourceManager.GetString("UnitCars", resourceCulture);
            }
        }
        
        internal static string AddVehicle {
            get {
                return ResourceManager.GetString("AddVehicle", resourceCulture);
            }
        }
        
        internal static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        internal static string MaxLot {
            get {
                return ResourceManager.GetString("MaxLot", resourceCulture);
            }
        }
        
        internal static string Bath {
            get {
                return ResourceManager.GetString("Bath", resourceCulture);
            }
        }
        
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        internal static string PayQrCode {
            get {
                return ResourceManager.GetString("PayQrCode", resourceCulture);
            }
        }
        
        internal static string PayCreditCard {
            get {
                return ResourceManager.GetString("PayCreditCard", resourceCulture);
            }
        }
        
        internal static string ConfirmPayment {
            get {
                return ResourceManager.GetString("ConfirmPayment", resourceCulture);
            }
        }
        
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        internal static string VehicleDetail {
            get {
                return ResourceManager.GetString("VehicleDetail", resourceCulture);
            }
        }
        
        internal static string LicensePlate {
            get {
                return ResourceManager.GetString("LicensePlate", resourceCulture);
            }
        }
        
        internal static string PleaseInputLicensePlate {
            get {
                return ResourceManager.GetString("PleaseInputLicensePlate", resourceCulture);
            }
        }
        
        internal static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        internal static string PleaseInputProvince {
            get {
                return ResourceManager.GetString("PleaseInputProvince", resourceCulture);
            }
        }
        
        internal static string maker {
            get {
                return ResourceManager.GetString("maker", resourceCulture);
            }
        }
        
        internal static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        internal static string PleaseInputMaker {
            get {
                return ResourceManager.GetString("PleaseInputMaker", resourceCulture);
            }
        }
        
        internal static string PleaseInputModel {
            get {
                return ResourceManager.GetString("PleaseInputModel", resourceCulture);
            }
        }
        
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        internal static string PleaseInputYear {
            get {
                return ResourceManager.GetString("PleaseInputYear", resourceCulture);
            }
        }
        
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        internal static string PleaseInputColor {
            get {
                return ResourceManager.GetString("PleaseInputColor", resourceCulture);
            }
        }
        
        internal static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        internal static string PleaseInputVehicleType {
            get {
                return ResourceManager.GetString("PleaseInputVehicleType", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string Notify {
            get {
                return ResourceManager.GetString("Notify", resourceCulture);
            }
        }
        
        internal static string mesCannotSelectMore {
            get {
                return ResourceManager.GetString("mesCannotSelectMore", resourceCulture);
            }
        }
        
        internal static string PleaseSelectStartDate {
            get {
                return ResourceManager.GetString("PleaseSelectStartDate", resourceCulture);
            }
        }
        
        internal static string PleaseSelectVehicle {
            get {
                return ResourceManager.GetString("PleaseSelectVehicle", resourceCulture);
            }
        }
        
        internal static string mesCannotMinusMaxCar {
            get {
                return ResourceManager.GetString("mesCannotMinusMaxCar", resourceCulture);
            }
        }
        
        internal static string mesCannotAddCocurrent {
            get {
                return ResourceManager.GetString("mesCannotAddCocurrent", resourceCulture);
            }
        }
        
        internal static string CannotMinusCocurrent {
            get {
                return ResourceManager.GetString("CannotMinusCocurrent", resourceCulture);
            }
        }
    }
}
