//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkXUI.Resources.Views.FindCarpark {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ParkXUI.Resources.Views.FindCarpark.index", typeof(index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string menu_home {
            get {
                return ResourceManager.GetString("menu_home", resourceCulture);
            }
        }
        
        internal static string menu_findCarPark {
            get {
                return ResourceManager.GetString("menu_findCarPark", resourceCulture);
            }
        }
        
        internal static string parkX {
            get {
                return ResourceManager.GetString("parkX", resourceCulture);
            }
        }
        
        internal static string ManagedParkX {
            get {
                return ResourceManager.GetString("ManagedParkX", resourceCulture);
            }
        }
        
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        internal static string mapImage {
            get {
                return ResourceManager.GetString("mapImage", resourceCulture);
            }
        }
        
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        internal static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
    }
}
