//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkXUI.Resources.Views.ParkingSolutions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AboutParkX {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutParkX() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ParkXUI.Resources.Views.ParkingSolutions.AboutParkX", typeof(AboutParkX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        internal static string ParkDescription {
            get {
                return ResourceManager.GetString("ParkDescription", resourceCulture);
            }
        }
        
        internal static string ParkList {
            get {
                return ResourceManager.GetString("ParkList", resourceCulture);
            }
        }
        
        internal static string vision {
            get {
                return ResourceManager.GetString("vision", resourceCulture);
            }
        }
        
        internal static string mission {
            get {
                return ResourceManager.GetString("mission", resourceCulture);
            }
        }
        
        internal static string ourvalue {
            get {
                return ResourceManager.GetString("ourvalue", resourceCulture);
            }
        }
    }
}
